### ISSUE TITLE
IDEA for user acquisition & retention: "best tracks" newsletter

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#108]
Ideas from Quentin Del. (🇫🇷):

> Tu pourrais envoyer une newsletter avec les sons les plus populaires postes sur la plateforme
automatiquement, un peu a la product hunt.
> Pour le site https://www.alexaskillstore.com, je fais [ca](http://us13.campaign-archive.com/?e=bdb491df8e&u=08c5c395bfdc2457be5e4c2b4&id=b95f39840f). => ca me booste le traffic + la retention. Si on regarde mon GA, j'ai de gros pics à chaque fois sur le shooting de la newsletter. Avec 100k emails, ca peut avoir son effet.

> Deuxième suggestion: travailler sur la mise en avant des curateurs, un comme sur product hunt: plus tu postes et t'as des likes, plus tu deviens influent. => le 'Hunter' est très mis en avant. C'est assez lié à la newsletter. Si je sais que mon nom est affiché sur la prochaine newsletter ca peut me motiver a participer et peut-être inciter le curateur a progresser dans le partage de sa chaine en lui donnant des metrics: nombre de lecture de ses sons postés, etc... Comme ca, il se dit "super le taf de curation que je fais est hyper utile, je vais continuer".

> Travailler sur un système equivalent au système d'abonnés Youtube ou dès que le curateur poste un son, ses abonnés reçoivent une newsletter.

> Bref, quelques idées pour augmenter l'acquisition et la retention de manière organique ! 🙂

> Notes:
> - l'emailing coute assez cher en fonction de l outil utilisé donc ca risque de rajouter des frais non négligeables. Mais un petit lien 'Soutiens Open whyd' dans chaque email, ca peut ramener quelques soutiens.
> - shooter un email régulier a 100k personnes, ca peut aussi intéresser des advertiser. Si le mailing a de bonnes metrics, ca peut rapporter au moins quelques centaines d'euros par shooting.

=> If you want to help, feel free to translate these ideas into English!

**Comment by QuentinDela** [comment]
Here is a quick english sum up : 
We could add a weekly newsletter with the most popular new sounds based on followed genre or users. It would be an opportunity to discover new sounds, to highlight the work of the best curators and to engage more people to use the website regularly. The current base has more than 100k+ emails so it would have a sensible impact on the traffic and so maybe the donations :).
