### ISSUE TITLE
Remove the "hide video" button

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#11]
Youtube contacted us to ask us to remove the possibility to hide the video while playing their content.

Basically, the only thing that we need to do is to hide the corresponding icon from the footer / player bar:

<img width="254" alt="screenshot 2016-09-25 18 05 49" src="https://cloud.githubusercontent.com/assets/531781/18816463/cad8fb78-834a-11e6-85b1-1cca3f2592f3.png">

Anyone down for making this quick easy change?

**Comment by Djiit** [comment]
Je prends! PR à suivre

**Comment by Djiit** [comment]
Voir #12
