### ISSUE TITLE
[UI] improve onboarding and calls to action: add a track, discover people to follow

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#163]
When creating a new account on Openwhyd, the user has to go through several onboarding steps (see below) which can be annoying, but is not given any clues about how to add tracks and discover new people after following (or skipping) this onboarding.

Reducing the number of steps of the onboarding process and providing clearer calls to action can result to better conversion (i.e. creating an account --> adding your first track).

Current steps of the onboarding process:
- from home page, click on "Sign up" button
- 1. fill in full name, email and password
- 2. pick favorite genres of music
- 3. select suggested people to follow
- 4. suggest to install the bookmarklet or google chrome extension to add tracks from other pages
- 5. display what and how personal data is stored by openwhyd and ask for consent (gdpr)
- 6. welcome page: display the user's stream with an overlay to explain what is the stream
- then, after clicking again, the user can finally interact with their new openwhyd account

=> that's 6 steps to follow (after clicking on "sign up")

Idea: steps ii, iii, iv and vi could be removed if we:
- directly take the new user to their stream page, right after filling the user info and giving consent
- propose 3 calls to action on their empty stream: "pick people to follow" (--> steps ii and iii), "add a track by searching" (would explain how to add tracks using the search bar) and "add a track from another page" (--> step iv).
- step vi may become useless, because the user could see tracks and recognize faces in the stream after explicitly deciding to follow people, if they ever do.
- also, the "add a track" calls to actions could be displayed on any list of tracks: stream + profile page + platlist page, to assist users who may have forgotten how to do that

**Comment by g180** [comment]
I like the idea. Killing the drag would make things handy. Maybe it would be kind enough if you leave a link that says something like "View Onboarding Massages Again" on "Settings" page or somewhere.

**Comment by adrienjoly** [comment]
We got only 2 replies to our call for "suggested users": https://www.facebook.com/groups/openwhyd/permalink/2791052064509668/ => let's remove that user suggestion feature used during the onboarding process.
