### ISSUE TITLE
Include "refacto" and "chore" commits in releases created by semantic-release

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#171]
*[openwhyd.org](https://openwhyd.org) is an open-source music platform used daily by thousands of users to create playlists of songs from the web (Youtube, Soundcloud, etc...), and discover musical gems from similar users.*

*Tech stack: Node.js, MongoDB, Docker, Mocka, Webdriver.io, jQuery, Electron + iOS app*

---

#### Goal

semantic-release automatically creates a github release after commits are merged into master.

it automatically bumps the version number (major, minor, or patch) according to the commit message. (e.g. `breaking`, `feat`, `fix`, `chore`...)

it's ok to not bump the version number for commits that do not have an impact for users (e.g. `chore` or `refacto`), but I would like them to still be listed in each github release.

solutions to be tried:
- https://github.com/semantic-release/semantic-release/issues/225
- https://github.com/semantic-release/commit-analyzer-v2/issues/12

---

#### Howto

In order to solve this issue, you are invited to fork this GitHub repository, makes changes to it, and then create a Pull Request so we can merge your changes back to this repository.

First, you may want to read about:
- How to install, setup and run Openwhyd on your computer: [`INSTALL.md`](https://github.com/openwhyd/openwhyd/blob/master/docs/INSTALL.md)
- How to propose a valuable contribution to this repo: [`CONTRIBUTING.md`](https://github.com/openwhyd/openwhyd/blob/master/docs/CONTRIBUTING.md)

I will be happy to assist you at any stage, if you want to try to solve this issue! If you have any question, just leave a comment below. Beginners are also welcome! 🤗

**Comment by Brawrdon** [comment]
I'd like to give this a go!

I think it's possible to include the notes in incrementing releases with:

```
"analyzeCommits": {
      "preset": "angular",
      "releaseRules": [
        {"type": "chore", "release": "patch"},
        {"type": "refactor", "release": "patch"}
      ]
    },
```

I'll take a proper look when I'm home!

**Comment by Brawrdon** [comment]
I'm still new to npm and I've never used the semantic releasing package. Are there any instructions for setting it up on my fork to automatically update the changelong there? `npm run semantic-releasing` seems to produce a compare but I'm not sure where I can view the generated notes.

**Comment by adrienjoly** [comment]
Hi Brawrdon! Thanks for your help!

As defined in [openwhyd's `package.json`](https://github.com/openwhyd/openwhyd/blob/master/package.json), the command to run is
`npm run semantic-release`.

That command will actually bump the version number specified in `package.json` if one or more conventional commits have been added since the last version's `git tag`. Cf [release steps](https://www.npmjs.com/package/semantic-release#release-steps).

When a new version is created, the notes should normally be generated in the repo's `CHANGELOG.md` file and in the repo's **Releases** tab.

So far, we've been running the `semantic-release` command on travis-ci only, and I don't remember if I ever ran it locally... But I will do my best to provide you with some guidance :-)

If this is not happening in your fork, you may want to try:
- making sure that you create a "Release" with Openwhyd's current version, from GitHub.com (you can copy the latest one from https://github.com/openwhyd/openwhyd/releases)
- fetch all the tags from your remote to your local repo, so that the release tag can be found locally
- create a dummy conventional commit (e.g. `fix(doc): test`)
- run `npm run semantic-release` from your local repo
- check that the version was incremented in `package.json`, and that `CHANGELOG.md` was updated

If it still does not work, I'm guessing that the `semantic-release` command may give you some useful feedback => please share it here.

**Comment by adrienjoly** [comment]
Good job for this progress, Brandon! 💪

Did you create a `chore` commit first? I don't see it in your forked repo: https://github.com/Brawrdon/openwhyd/commits/master

**Comment by Brawrdon** [comment]
They haven't been pushed yet!

**Comment by adrienjoly** [comment]
Ok, so after running `npm run semantic-release`, you don't see any changes as listed by `git status` ?

**Comment by Brawrdon** [comment]
No changes listed by `git status`

This is the whole output:

```
[10:46:02 AM] [semantic-release] » i  Running semantic-release version 15.9.15
[10:46:02 AM] [semantic-release] » √  Loaded plugin "verifyConditions" from "@semantic-release/github"
[10:46:02 AM] [semantic-release] » √  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:46:02 AM] [semantic-release] » √  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:46:02 AM] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/changelog"
[10:46:02 AM] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/npm"
[10:46:02 AM] [semantic-release] » √  Loaded plugin "prepare" from "@semantic-release/git"
[10:46:02 AM] [semantic-release] » √  Loaded plugin "publish" from "@semantic-release/github"
[10:46:03 AM] [semantic-release] » i  This run was not triggered in a known CI environment, running in dry-run mode.
[10:46:03 AM] [semantic-release] » √  Run automated release from branch master
[10:46:11 AM] [semantic-release] » √  Allowed to push to the Git repository
[10:46:11 AM] [semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/github"
[10:46:11 AM] [semantic-release] [@semantic-release/github] » i  Verify GitHub authentication
[10:46:12 AM] [semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/github"
[10:46:13 AM] [semantic-release] » i  Found git tag v1.4.2 associated with version 1.4.2
[10:46:14 AM] [semantic-release] » i  Found 7 commits since last release
[10:46:14 AM] [semantic-release] » i  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:46:14 AM] [semantic-release] [@semantic-release/commit-analyzer] » i  Analyzing commit: chore(config): changed
[10:46:14 AM] [semantic-release] [@semantic-release/commit-analyzer] » i  The release type for the commit is major
[10:46:14 AM] [semantic-release] [@semantic-release/commit-analyzer] » i  Analysis of 7 commits complete: major release
[10:46:14 AM] [semantic-release] » √  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:46:14 AM] [semantic-release] » i  The next release version is 2.0.0
[10:46:14 AM] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:46:14 AM] [semantic-release] » √  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:46:14 AM] [semantic-release] » i  Release note for version 2.0.0:
# 2.0.0 (https://github.com/brawrdon/openwhyd/compare/v1.4.2...v2.0.0) (2018-10-09)

### Bug Fixes

    * doc: test (8203428 (https://github.com/brawrdon/openwhyd/commit/8203428))
    * docs: test (b414a90 (https://github.com/brawrdon/openwhyd/commit/b414a90))
```

It lists a major, bit doesn't display chore commits

**Comment by adrienjoly** [comment]
So I'm guessing that you have two problems:
1. running `semantic-version` locally does not update the `CHANGELOG.md` file
2. the `analyzeCommits` rule that you added does not trigger a version bump, as you had expected

As you're not running `semantic-version` from travis-ci (like we do for openwhyd's main repo), I would start by investigating the problem 1 first, if I were you. E.g. by looking online how to make `semantic-release` update the `CHANGELOG.md` file, when run locally, even for a `fix` commit.

And only when that works, I would investigate problem 2: find out how to configure `semantic-version` to make it work for `chore` commits.

**Comment by Brawrdon** [comment]
I think semantic-release isn't updating because I'm doing it locally, I noticed the fact it automatically does a "dry run".

I think I solved it! Placing `BREAKING CHANGE` into the footer of commits (after some more configuration) would solve the problem. Stumbling upon [this changelog](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-codemirror/CHANGELOG.md), it seems to be using the default configurations; angular preset and so on. However, when looking at the commits labeled as chore and refactoring, they both have BREAKING CHANGES at the start of their header.

I'm now looking to see if it would work by changing `noteKeywords`!

**Comment by Brawrdon** [comment]
So this seems to work!

```
"analyzeCommits" : {
      "preset": "angular",
      "releaseRules": [
        {"type": "chore", "release": "patch"},
        {"type": "refactor", "release": "patch"}
      ]
    },
    "generateNotes" : {
      "preset": "angular",
      "parserOpts": {
        "noteKeywords": ["CHORE", "REFACTOR"]
      },
      "writerOpts": {
        "commitsSort": ["subject", "scope"]
      }
    },
```

This produces

```

### chore

    * config: more semantic release (dd38af8 (https://github.com/brawrdon/openwhyd/commit/dd38af8))

### Code Refactoring

    * config: added a space (2b06312 (https://github.com/brawrdon/openwhyd/commit/2b06312))

### BREAKING CHANGES

    * config: Did it again
    * config: I did it

```

Manually editing the angular preset file allows me change `chore` to `Chore` and also change the headings of the "breaking changes" per commit. However this doesn't seem practical. This also looks like the best I can do considering the configuration options give.

For reference here is the git log:
```
commit 114c1e443ef30a274e2e1f5d70b23d0a70ff863d (HEAD -> master)
Author: Brawrdon <BrandonOkeke@gmail.com>
Date:   Tue Oct 9 20:08:56 2018 +0100

    refactor(package): remove whitespace
    REFACTOR:

commit eca1bf53c8385ecf792e185cedee7205297805a3
Author: Brawrdon <BrandonOkeke@gmail.com>
Date:   Tue Oct 9 19:52:58 2018 +0100

    chore(hello): yes

commit 2b063125e8330e1983f5dedc8853459f65689254
Author: Brawrdon <BrandonOkeke@gmail.com>
Date:   Tue Oct 9 19:48:41 2018 +0100

    refactor(config): added a space
    REFACTOR:
    
    Did it again

commit dd38af851aeda4b160429c32660890e78a4237cb
Author: Brawrdon <BrandonOkeke@gmail.com>
Date:   Tue Oct 9 19:47:37 2018 +0100

    chore(config): more semantic release
    CHORE:

    I did it

commit 709d39f96918eaf5efcf4e83a7d318c9aee615a8
Author: Brawrdon <BrandonOkeke@gmail.com>
Date:   Tue Oct 9 19:46:17 2018 +0100

    chore(again): break
    BREAKING CHANGE:
    
    Urm

commit 0056a10910a47326d7adecbd49691fee3d32d3cd
Author: Brawrdon <BrandonOkeke@gmail.com>
Date:   Tue Oct 9 19:39:24 2018 +0100

    chore(config): change semantic release
    CHORE
    
    Testing with some stuff here

commit cf6cf48e8e97c97c461f2fce7134f2cd47524398 (origin/master, origin/HEAD)
Author: Adrien Joly <531781+adrienjoly@users.noreply.github.com>
Date:   Tue Oct 2 10:38:25 2018 +0200

    chore(github): add feature_request issue template
```

**Comment by Brawrdon** [comment]
It essentially works by requiring `CHORE:` or `REFACTOR` after the subject, a new line and then more details. These more details are placed under `BREAKING CHANGES`. I've also set the configuration to increment by a patch (default major because they are technically breaking changes) and I'm not sure if that is correct

**Comment by Brawrdon** [comment]
So this seems to work!

```
"analyzeCommits" : {
      "preset": "angular",
      "releaseRules": [
        {"type": "chore", "release": "patch"},
        {"type": "refactor", "release": "patch"}
      ]
    },
    "generateNotes" : {
      "preset": "angular",
      "parserOpts": {
        "noteKeywords": ["CHORE", "REFACTOR"]
      },
      "writerOpts": {
        "commitsSort": ["subject", "scope"]
      }
    },
```

This produces

```

### chore

    * config: more semantic release (dd38af8 (https://github.com/brawrdon/openwhyd/commit/dd38af8))

### Code Refactoring

    * config: added a space (2b06312 (https://github.com/brawrdon/openwhyd/commit/2b06312))

### BREAKING CHANGES

    * config: Did it again
    * config: I did it

```

Manually editing the angular preset file allows me change `chore` to `Chore` and also change the headings of the "breaking changes" per commit. However this doesn't seem practical. This also looks like the best I can do considering the configuration options give.

For reference here is the git log:
```
commit 114c1e443ef30a274e2e1f5d70b23d0a70ff863d (HEAD -> master)
Author: Brawrdon <email@gmail.com>
Date:   Tue Oct 9 20:08:56 2018 +0100

    refactor(package): remove whitespace
    REFACTOR:

commit eca1bf53c8385ecf792e185cedee7205297805a3
Author: Brawrdon <email@gmail.com>
Date:   Tue Oct 9 19:52:58 2018 +0100

    chore(hello): yes

commit 2b063125e8330e1983f5dedc8853459f65689254
Author: Brawrdon <email@gmail.com>
Date:   Tue Oct 9 19:48:41 2018 +0100

    refactor(config): added a space
    REFACTOR:
    
    Did it again

commit dd38af851aeda4b160429c32660890e78a4237cb
Author: Brawrdon <email@gmail.com>
Date:   Tue Oct 9 19:47:37 2018 +0100

    chore(config): more semantic release
    CHORE:

    I did it

commit 709d39f96918eaf5efcf4e83a7d318c9aee615a8
Author: Brawrdon <email@gmail.com>
Date:   Tue Oct 9 19:46:17 2018 +0100

    chore(again): break
    BREAKING CHANGE:
    
    Urm

commit 0056a10910a47326d7adecbd49691fee3d32d3cd
Author: Brawrdon <email@gmail.com>
Date:   Tue Oct 9 19:39:24 2018 +0100

    chore(config): change semantic release
    CHORE
    
    Testing with some stuff here

commit cf6cf48e8e97c97c461f2fce7134f2cd47524398 (origin/master, origin/HEAD)
Author: Adrien Joly <531781+adrienjoly@users.noreply.github.com>
Date:   Tue Oct 2 10:38:25 2018 +0200

    chore(github): add feature_request issue template
```

**Comment by Brawrdon** [comment]
By default it needs to include `BREAKING CHANGES:`. `CHORE` works with the configuration I've set

**Comment by adrienjoly** [comment]
Ok, but so it's not gonna work if the commit message is just "chore: whatever", without line break and uppercase `CHORE`. Or is it?

**Comment by Brawrdon** [comment]
Not the commit would have to be something like

```
chore(scope): subject
CHORE:

Message about breakage here 
```

**Comment by adrienjoly** [comment]
I'm afraid that this workaround seems more complicated than just using `fix` instead of `chore`... Is it worth merging as-is, in your opinion?

**Comment by Brawrdon** [comment]
I'll give it another check when I can to see if there's an easier way!

**Comment by Brawrdon** [comment]
I think it'll be best to stick to that format as it is a convetion.

**Comment by adrienjoly** [comment]
Fair enough. So I guess that we can close that issue. Thank you for your investigation, anyway! :-)

Would you be interested in proposing a contribution on another topic, for openwhyd? I can help you find an interesting one, if you tell me more about what topic/stack you'd enjoy contributing on :-)

**Comment by Brawrdon** [comment]
That's okay! I would be up to that 100%! I've been looking at ones for replacing packages, they seem like a nice place to start. I'm actually fairly new to node, I've only used it to create hacky scripts quickly because the things I found where in JavaScript, so I still have a lot to learn about its ecosystem etc. In terms of stack, any!

**Comment by adrienjoly** [comment]
Awesome! I'm happy that you want to contribute!

I don't know if you've ever used openwhyd.org or not at that point. If so, you way know that the contributions that would make the biggest impact for users are:
- providing a way to listen to your openwhyd playlists on android (https://github.com/openwhyd/openwhyd-react/issues/2)
- fix the web player so that youtube tracks can be played sequentially even in the background (https://github.com/openwhyd/openwhyd/issues/132)
- and fix streaming players that don't always work as expected (e.g. bandcamp), as listed in the "roadmap" column of https://github.com/openwhyd/openwhyd/projects/1 

(note that the web players are actually maintained in a separate repository: https://github.com/openwhyd/openwhyd/blob/master/docs/playemjs-fix-procedure.md)

Also, one alternative approach to improve openwhyd's UI, multi-platform support (e.g. android) and music playback would be to develop a new front-end for it. For instance, @SkinyMonkey made a React front-end from scratch: https://github.com/openwhyd/openwhyd-react/issues/2. He stopped maintaining it because openwhyd's lack of OAuth-based API (https://github.com/openwhyd/openwhyd/issues/55) forced him to run a small back-end/bridge online, which was not free. If somebody provided a way for front-end clients to auth & connect to openwhyd's API without requiring to host and run such a back-end bridge, it would be much easier for the community to create and maintain openwhyd clients for several platforms! So that's yet another impactful contribution that could be made.

I'm closing this issue for now, but we can keep writing in this thread if you want :-)
