### ISSUE TITLE
Replace old logo from Openwhyd's embed player

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#183]
Related to #7.

Example of embed: http://www.musiclikedirt.com/2018/10/12/top-tracks-of-the-month-october-2018/

name of image: `/images/logo-verysmall.png` (to be replaced by new logo)

**Comment by namanbiyani** [comment]
i have made a pull request

**Comment by adrienjoly** [comment]
Thank you for your first contribution to Openwhyd, @namanbiyani! You did great! <3

If you don't mind, in order to make this repository a friendlier to contributors, I'd like to ask you a few questions:

1. How much experience do you have with contributing to open source projects?
2. Did you enjoy contributing to Openwhyd? Please explain what was good and what could be improved.
3. Would you like to contribute to Openwhyd again? If so, can you tell us what kind of contributions your would like to make next.
4. How did you know about openwhyd.org and/or this open source project?
5. What motivated you to contribute to Openwhyd?

If you don't feel comfortable replying to these questions here, feel free to respond in private to adrien@openwhyd.org. I look forward to reading from you! ^^

Thank you again!

**Comment by namanbiyani** [comment]
Yes I enjoyed it , this was my first contribution in github . Please send me notifications of resolving bugs later also if possible.

**Comment by adrienjoly** [comment]
Congratulations for your first open-source contribution and thank you for having chosen Openwhyd! 🎉

When would you be available to resolving bugs?

**Comment by adrienjoly** [comment]
Hello again, @namanbiyani ! How are you?

If you are interested in fixing other bugs, here are a few ones that are a bit more complicated but for which a fix would be very appreciated by the community:
- [Soundcloud tracks sometimes don't play · Issue #128 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/128)
- [Bandcamp tracks playback fail · Issue #117 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/117)
- [Fix the player so that tracks can be played in the background without skipping any · Issue #132 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/132)

Would you like to have a look? I'm happy to reply to your questions and provide assistance if needed!
