### ISSUE TITLE
can't add new youtube tracks

### ISSUE THREAD

**Issue by tomerrr** [openwhyd/openwhyd#192]
console shows

``
2/2 list streamable tracks...
apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:149 GET https://content.googleapis.com/youtube/v3/videos… 403
zu @ apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:149
n @ apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:149
Cu @ apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:150
(anonymous) @ apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:150
g @ apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:126
c @ apis.google.com/…/rs=AGLTcCNo3EDgCfnM5…/cb=gapi.loaded_0:122
playem-min.js?1551713395824:2 Uncaught TypeError: Cannot read property 'map' of undefined
at playem-min.js?1551713395824:2
at cb=gapi.loaded_0:694
at cb=gapi.loaded_0:689
at cb=gapi.loaded_0:678
at Object.<anonymous> (cb=gapi.loaded_0:198)
at Object.E.__cb (cb=gapi.loaded_0:135)
at g (cb=gapi.loaded_0:129)
at c (cb=gapi.loaded_0:125)
``

**Comment by adrienjoly** [comment]
Thanks Tomer!

Could be related to #190. But it's weird because automated tests passed...

**Comment by adrienjoly** [comment]
That's the final error I'm getting, from the HTTP request to YouTube's API:

```json
{
error: {
errors: [
{
domain: "usageLimits",
reason: "dailyLimitExceeded",
message: "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=345430738996",
extendedHelp: "https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=345430738996"
}
],
code: 403,
message: "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=345430738996"
}
}
```

Indeed, the API key I had created in #190 seems to have a quota of just 10k calls per day:

![image](https://user-images.githubusercontent.com/531781/53788871-4d03a300-3f23-11e9-8b5d-cd8d8e229b77.png)

**Comment by adrienjoly** [comment]
Until I find a solution, I reverted back to our previous YouTube API key. This should work for now.
