### ISSUE TITLE
UX BUG: resizing the pages scrolls to the top

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#20]
https://twitter.com/StevenJeuris/status/782203830280851456:

Resizing @open_whyd window scrolls page all the way to the top. Annoying in long playlists. Also triggered by search in Edge. #hcifail

**Comment by adrienjoly** [comment]
@damienromito coucou!

rien de grave ni urgent, mais je voulais savoir si je pouvais retirer cette ligne de code: https://github.com/whyd/whyd/blame/master/whydJS/public/js/whyd.js#L34

vu que c'est toi qui l'avais ajoutée, je me demande si tu avais une bonne raison pour qu'elle y reste, ou pas.

merci d'avance pour ta réponse!

**Comment by compiuta** [comment]
@adrienjoly je décider de retiré cette ligne de code pour retiré le bug :smile:

**Comment by adrienjoly** [comment]
Je savais pas que tu parlais français, @compiuta ! Du coup, est-ce qu'on s'est déjà rencontrés ?

**Comment by compiuta** [comment]
Je ne parle pas français trop bien mais je parle espagnol et je besoin de practique beucoup plus me français :grin: 

Nunca nos hemos encontrado en persona

**Comment by adrienjoly** [comment]
@compiuta ¡tu francés es mejor que mi español! Estoy encantado de conocerte! :-)

(thank you, google translate, ahah!)
