### ISSUE TITLE
Prevent "use desktop/electron app" error message ...when using that app!

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#224]
**Describe the bug**

A few years ago, Google Chrome prevented videos from being played without user intervention, when the tab is not focused.

In order to not let new users think that Openwhyd is not able to play tracks sequentially because of that new behavior, I decided to pause the playback whenever the user would switch to another track, so that they can see the following recommendation:

> Oops, we could not play this track... Please try with Openwhyd Desktop App 👌

Indeed, the "Openwhyd Desktop App" (downloadable from https://openwhyd.org/download) is able to play tracks sequentially, even in the background.

Unfortunately, that same error message is displayed every time a track fails to be played, for any reason, including from the Openwhyd Desktop App itself! 😬

**To Reproduce**

1. Start the Openwhyd Desktop App (you can download the latest versionfrom https://openwhyd.org/download)
2. Open the following posted track from the App: https://openwhyd.org/c/53035251200c8a63270004b3
3. Play the track, it should display the error message

**Expected behavior**

When a track fails to play from the Desktop App, it should displayed another error message. Something like:

> Oops, we could not play this track...

But, when failing to play that track from openwhyd.org (in Google Chrome), the error message should be left as it currently is. (i.e. invite the user to install the Desktop App)

**Screenshots**

Here's what the error looks like:

![Capture d’écran 2020-03-15 à 11 10 04](https://user-images.githubusercontent.com/531781/76699560-ddd09b00-66ae-11ea-9545-cdf7685de753.png)

You can find the implementation of that error message in `whydPlayer.js`

**Comment by compiuta** [comment]
@adrienjoly there are 2  issues when trying to test a solution on my local machine.

I have used a solution suggested here https://github.com/electron/electron/issues/2288#issuecomment-337858978

1) For some reason when searching for anything on my local install of openwhyd I never seem to get any results. Let me know if this is just on my machine or if you are having the same issue.

![Screenshot from 2020-03-19 14-39-15](https://user-images.githubusercontent.com/13477167/77117567-848aa380-69ef-11ea-924d-71b83a9c0f66.png)

2) Is there an easy way to test changes on the electron app locally?

**Comment by adrienjoly** [comment]
> For some reason when searching for anything on my local install of openwhyd I never seem to get any results. Let me know if this is just on my machine or if you are having the same issue.

@compiuta It's expected. Search is provided by a third-party: Algolia, and the Algolia credentials provided in the `env-vars-testing` of this repository are read-only.

 If you want your local search index to be populated after adding tracks, you should create an Algolia account, and set the `ALGOLIA_APP_ID` and `ALGOLIA_API_KEY` [environment variables](https://github.com/openwhyd/openwhyd/blob/master/docs/INSTALL.md#environment-variables) accordingly.

**Comment by adrienjoly** [comment]
> Is there an easy way to test changes on the electron app locally?

@compiuta Yes, there is:
1. run openwhyd locally (e.g. on port 8080)
2. clone https://github.com/openwhyd/openwhyd-electron on your computer
3. change its code so it opens http://localhost:8080 instead of https://openwhyd.org

Btw, the openwhyd-electron repository could benefit from more documentation. Feel free to send a Pull Request there if you want to propose some!

Adrien

**Comment by adrienjoly** [comment]
@compiuta I also wanted to let you know that we already had some code in openwhyd's repository to check if it's running in electron.

A quick search for "electron" in the source code reveals a `getBrowserVersionFromUserAgent()` function in `app/contollers/api/post.js`, which detects openwhyd-electron from the user agent.

You can probably re-use a similar logic in the front-end, as the user agent is made available by the browser.

**Comment by compiuta** [comment]
I will try out your suggestions and get back to you later :+1:

**Comment by compiuta** [comment]
@adrienjoly I was able to test the electron app locally and a variable that exists in the whydPlayer.js file USING_ELECTRON is actually already detecting if we are in the electron app.

I added to the if condition let me know if the message is now changing for you when using the electron app or an internet browser.
