### ISSUE TITLE
never-ending loading animation on empty search

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#226]
From #213

Also, doing a " " search on openwhyd.org results in a never-ending loading animation + errors in js console + `content.bundle.js.map` user profile trying to be opened! (from server logs)

<img width="516" alt="Capture d’écran 2019-09-24 à 21 24 15" src="https://user-images.githubusercontent.com/531781/65543711-ffc43e80-df11-11e9-8086-c49d0376d782.png">

<img width="729" alt="Capture d’écran 2019-09-24 à 21 24 15 copie" src="https://user-images.githubusercontent.com/531781/65543716-02269880-df12-11e9-97d7-8367a40ac3a4.png">

**Comment by compiuta** [comment]
I made some updates to my bug fix and it now includes a change to the quickSearch,js file. The change will make the keydown event function return ff there is an empty search field. 

This will prevent the loading screen from ever appearing if the user searches for an empty string.
