### ISSUE TITLE
BUG: Youtube profile link does not work (adds /user/ in the URL)

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#23]
> the youtube url on my profile does not work, it automatically inserts "user" in the middle of the url, which makes it bounce

source: https://twitter.com/dededehors/status/795314405953142785

**Comment by Marinlemaignan** [comment]
Hey, this is not the way it behaves on my profile... mine works just fine, is that normal?

**Comment by adrienjoly** [comment]
i have no idea. i didn't receive any other complaint on that topic. i just keep it open, just in case.
