### ISSUE TITLE
BUG: Search/filter feature on profile page for tracks does not work

### ISSUE THREAD

**Issue by Marinlemaignan** [openwhyd/openwhyd#27]
Might be related to https://github.com/openwhyd/openwhyd/issues/13 ?
Inspection in console's network tab seems to return a 200 with an empty body.

**Comment by adrienjoly** [comment]
Yes, it could be, @Marinlemaignan ...

I think that posted tracks have not been indexed by algolia for a few months now.

Any suggestion to solve this problem?

**Comment by adrienjoly** [comment]
Also reported by [Chowee Stardusst](https://www.facebook.com/chowee) by [FB private message](https://www.facebook.com/openwhyd/messages/?threadid=709212966&timestamp=1491226165644):

> your search engine to find a track in our own track list seems to be broken, any clue ?

**Comment by adrienjoly** [comment]
diagnostic & fixing steps:

[ ] check if recent tracks were indexed by algolia
[ ] create a blank algolia account and test indexing from a local instance
[ ] update to latest version of algolia lib (cf #13)
[ ] fix search and filter
[ ] write automated test

**Comment by adrienjoly** [comment]
fixed in https://github.com/openwhyd/openwhyd/commit/1f66824258a964aa201d0f9bad0f3f9e4fd02136
