### ISSUE TITLE
Add support for twitter cards

### ISSUE THREAD

**Issue by greyvugrin** [openwhyd/openwhyd#29]
Ideally, sharing on Twitter would show the same nice cards that sharing to Facebook does.

It seems that it could be as easy as adding `<meta name="twitter:card" content="summary" />` to the head, since all open graph tags seem to be in place. If so I can submit a PR soon

**Comment by adrienjoly** [comment]
That's a very good idea!

Your PR would be welcome :-)

Let me know if you have any question!
