### ISSUE TITLE
404 when clicking load more on stream

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#295]
Reported by stefanos:

When trying to press the button “ Load More” in the stream of Openwhyd I get a 404 page

This happens in the browser and in the WHYD app too

**Comment by adrienjoly** [comment]
@Compiuta, would you be interested to have a look at this bug and see if there is anything to fix on the front end?

**Comment by compiuta** [comment]
I tried the load more button found in the home page and it looks like it is working.

Is there a specific page where this bug is happening? or is there a set of steps to take before getting this bug? :thinking:

**Comment by compiuta** [comment]
@adrienjoly Alright I signed in and now I can see the issue :sweat_smile: 

I will take a look and see if I can find anything
