### ISSUE TITLE
alphabetise/sort lists of playlists

### ISSUE THREAD

**Issue by yakrell** [openwhyd/openwhyd#371]
### problem
currently, playlists are sorted by order of creation.
this can make it difficult to find a particular playlist, especially in the posting dialogue, where you cannot see thumbnails or ctrl+f for the title like you could on the user playlists page.
### solution
sorting lists of playlists alphabetically would make this easier, perhaps selectable as one of several sorting options as seen in similar apps.
### potential implementation
we could achieve this by adding sorting functions to call whenever a list of playlist is created, or a different sort mode is selected. toying with the js console in the [chrome extension posting dialogue](https://openwhyd.org/post?v=2&embed=1&eId=%2Fyt%2F7neipvZ_H0c&title=Scatman%27s%20World&refUrl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7neipvZ_H0c&refTtl=Scatman%27s%20World%20-%20YouTube&text=), i found a solution that seems to work:

1. add an id to the playlist selection list ul ("list" in this case)
2. run this function (from this [stackoverflow reply](https://stackoverflow.com/a/30095613)) to sort the li elements alphabetically:

```
$(function() {

  var $list = $("#list");

  $list.children().detach().sort(function(a, b) {
    return $(a).text().localeCompare($(b).text());
  }).appendTo($list);

});
```
i am not sure how exactly the "No playlist" element stays at the top here, possibly the leading whitespace is getting sorted instead of the 'N'?
</br></br>
as a side note, i was attempting to use names to get around the lack of folders (playlist names starting with "myfolder/" would all appear together if alphabetical). i may open another issue for folders.

**Comment by compiuta** [comment]
@yakrell I have submitted a pull request for this https://github.com/openwhyd/openwhyd/pull/372
