### ISSUE TITLE
MD5 is an insecure way to hash and store passwords, and stolen passwords can be uncovered easily

### ISSUE THREAD

**Issue by jasperbogers** [openwhyd/openwhyd#425]
**Describe the bug**
MD5 is not an encryption mechanism for passwords. It's a fast hashing mechanism. If the database of passwords should ever be compromised, MD5 offers no security, unlike what is said in the GDPR consent form new users have to fill out upon sign up.

**To Reproduce**
1. See file https://github.com/openwhyd/openwhyd/blob/master/app/controllers/api/login.js . The logic there does an MD5 hash and comparison of the directly entered password, suggesting there's no other encryption going on.
2. See for example https://security.stackexchange.com/questions/19906/is-md5-considered-insecure#19908 or a range of other blogs explaining why MD5 should not be used for password hashing.
3. You don't even need to have a rainbow table to figure out MD5 values; it is in fact as simple as entering an MD5 hashed password in Google to find the unhashed value these days. 

**Expected behavior**
Use an encryption mechanism that cannot be decrypted easily, and use salting and key strengthening, as explained in https://en.wikipedia.org/wiki/Key_strengthening . BCrypt (https://en.wikipedia.org/wiki/Bcrypt) is still a safe way to apply this concept.

A known migration method for moving from the existing stored password hashes to the new encrypted ones, is by reencrypting passwords when existing users log in and storing those separately, as described here: https://stackoverflow.com/questions/1381448/how-do-i-convert-password-hashing-from-md5-to-sha . That way, your users won't have to take any further action to make their stored credentials more secrure other than logging in.

**Comment by adrienjoly** [comment]
Thanks for the feedback, Jasper, we appreciate it.
Openwhyd is a non profit project developed by volunteers during their spare time. We do our best to balance priorities.
As a matter of fact, we started working on this. See #258 for progress.

Would you be interested in helping us out with this task by submitting a pull request?

**Comment by jasperbogers** [comment]
Ah, good to hear! NodeJS isn't my forte, but I thought I could help out by raising the issue. I'm sorry I didn't notice https://github.com/openwhyd/openwhyd/issues/258 before. I can close this one as a duplicate? As I can see you've done your homework on that one, picking the newer Argon over BCrypt.

**Comment by adrienjoly** [comment]
Thanks for your reply, Jasper! Feel free to close this issue as a duplicate, if you want ^^

And if you know a developer who may be interested in contributing, please let them know that I'd be happy to assist them if necessary.
