### ISSUE TITLE
homeHeader div on main page blocks selecting items in the searchResults div

### ISSUE THREAD

**Issue by alightsleeper** [openwhyd/openwhyd#434]
**Describe the bug**
On the main page, when user begins text input to search and search results populates, the 1st item under "Posts" cannot be selected, as the header text "Openwhyd: The community of music lovers" and "Discover and collect music gems from Youtube, Soundcloud, Deezer and more" overlaps and blocks it:

![Screen Shot 2021-01-22 at 5 20 17 PM](https://user-images.githubusercontent.com/6707588/105559330-7c1d8c00-5cd6-11eb-99c7-6e9ca67ee17b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adrienjoly** [comment]
Thank you for reporting this issue and for proposing a fix for it, Dheeru!

I just merged it deployed it to production. (openwhyd.org)

Enjoy your weekend! ^^
