### ISSUE TITLE
Feature: 'Back' option when navigating in app on Mac

### ISSUE THREAD

**Issue by ElBurritoPodrido** [openwhyd/openwhyd#44]
Hi all,

Not sure if this is an issue or a feature request. I tried the app for mac yesterday for the first time - love it! I'm running Sierra 10.12.5
When I browse the site through the app, I can not "go back". 
For example, if I do the following:
- Go to a profile
- Browse playlists availables
- Open a playlists and browse it
I can not go back directly to browsing the available playlists. I need to go back to the profile, then open the playlists again.

It is a small enhancement, but it would make for a smoother navigation through the app, and it would be easier to explore the others' playlists.

**Comment by adrienjoly** [comment]
Hi @ElBurritoPodrido , thank you for posting this issue!

While I completely understand your problem, and wish that it would be solved.

That being said, don't you think that adding a "back" button to https://github.com/openwhyd/openwhyd-electron (the installable openwhyd app, for mac and other operating systems) would be more relevant than integrating it to the web version?

**Comment by ElBurritoPodrido** [comment]
My bad, I should have posted it there indeed. I'm relatively new to GitHub.
I'm creating it over there.
