### ISSUE TITLE
Add Openwhyd playlist syncing capabilities across various music streaming services and software.

### ISSUE THREAD

**Issue by Rabioli** [openwhyd/openwhyd#464]
_[openwhyd.org](https://openwhyd.org) is an open-source music platform used daily by thousands of users to create playlists of songs from the web (Youtube, Soundcloud, etc...), and discover musical gems from similar users._

_Tech stack: Node.js, MongoDB, Docker, Mocka, Webdriver.io, jQuery, Electron + iOS app_

## Goal

Openwhyd is a great website for making playlist, but it lacks integration with other services, in other words it is just yet another isolated island, it is just like any other music streaming site, with the difference that it is open and with some different features but still you manage and create your own playlist only in this platform (with the option of exporting it in not so friendly formats for music players and other platforms). My proposal is integrating a sync service along other sites like spotify, youtube, soundcloud, bandcamp, funkwhale and so on, of the playlist made here, regardless of the provider used and also being able to export this playlist as xspf or m3u, so they are easily manageable by other programs instead of the json that is not supported out of the box or without doing some format conversion. Simplified, add functionalities of sites like [tune my music](https://www.tunemymusic.com/) and [soundiiz](https://soundiiz.com/) and make Openwhyd a place to manage all playlist and share them all across all services through a kind of linktree for each playlist managed by it that links to all platforms synced.

For achieving this I was thinking in using apis of those services that clearly other sites already use, but also using metadata of songs by using musicbrainz or other musical database instead of just name and artist since this can result in many broken playlist being generated.

Funkwhale is already working in exporting and importing their playlist as xspf, so you may want to check a look at how they are doing it and also to consider for integration with funkwhale servers.

- [issue](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/836)
- [merge request](https://dev.funkwhale.audio/funkwhale/funkwhale/-/merge_requests/1298)

## Howto

I would be willing to work on this feature but I will need a lot of guidance and instruction since I barely code, and I am completely unfamiliar with your codebase, regardless of the answer I am planning on making this whether here or make it completely on my own.

**Comment by adrienjoly** [comment]
Hi @Rabioli,

Thanks for sharing your idea with us and for offering your help to develop it.

Unfortunately, I don't have enough time to provide proper guidance to somebody who is not experienced in software development, at the moment...

That said, here are a few suggestions that mat help you:
- if you want to try developing a way to export playlists in xspf or m3u format yourself, you can probably add a `else if` block with the corresponding file extension that would convert the JSON into that format, in https://github.com/openwhyd/openwhyd/blob/master/app/controllers/LibUser.js#L567, and then propose a pull request
- if you would like some assistance while contributing to openwhyd (or any other open source project), sign up to a "hackergarten" event near you, it's free and people are friendly

Hope this helps! 

Best regards,

Adrien
