### ISSUE TITLE
FEATURE: Improve design of playlist embed + enable deeper integration on external websites

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#50]
Several music curators love using Openwhyd, but want to distributing their selection thru their own website, while maintaining a good level of user experience and design consistency.

Openwhyd's playlist embed:
- has not been touched for about 3 years, 
- is still branded "whyd" instead of "Openwhyd",
- is very hard to fit esthetically on most websites.

<img width="842" alt="screen shot 2017-07-03 at 12 59 48" src="https://user-images.githubusercontent.com/531781/27790143-98c9e0b6-5fef-11e7-9a92-8856e4db0fc4.png">

Discussions are ongoing with Charles from musicdmc.com ("donne m'en cinq"), for the redesign on this playlist embed.

Note: I had started to work on a more generic player that could be embedded dynamically using JavaScript, rather than an iframe (i.e. the way it's done currently).

**Comment by cmdcmdcmd** [comment]
On it :)

**Comment by adrienjoly** [comment]
That's awesome!

PS: do we know each other?

**Comment by adrienjoly** [comment]
I just found my work in progress on an embedded player that can be loaded dynamically (i.e. by loading a JavaScript file, instead of integrating an iframe) and customized by its hosting page:

- source code of the dynamic player embed: [js/whydEmbed.js](https://github.com/openwhyd/openwhyd/blob/master/whydJS/public/js/whydEmbed.js)
- example of use: [demo](https://openwhyd.org/html/testWhydEmbed.html) (source code: [html](https://github.com/openwhyd/openwhyd/blob/master/whydJS/public/html/testWhydEmbed.html) + [css](https://github.com/openwhyd/openwhyd/blob/master/whydJS/public/html/testWhydEmbed.css))

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>New OpenWhyd Embed</title>
  <link rel="stylesheet" type="text/css" href='/html/testWhydEmbed.css'></link>
</head>
<body>
  <div id="coucou"></div>
  <script src='/js/whydEmbed.js?id=coucou&amp;path=https://openwhyd.org/u/53034dbe7e91c862b2b59270/playlist/1'></script>
</body>
</html>
```

```css
```

**Comment by adrienjoly** [comment]
Otherwise, you can find the previous and current version of the player embed in these files:

- v1: [app/templates/feedEmbed.html](https://github.com/openwhyd/openwhyd/blob/master/whydJS/app/templates/feedEmbed.html) + [css](https://github.com/openwhyd/openwhyd/blob/master/whydJS/public/css/feedEmbed.css)
- v2: [app/templates/feedEmbedV2.html](https://github.com/openwhyd/openwhyd/blob/master/whydJS/app/templates/feedEmbedV2.html) + [css](https://github.com/openwhyd/openwhyd/blob/master/whydJS/public/css/feedEmbedV2.css)

Both are loaded by [app/templates/feed.js](https://github.com/openwhyd/openwhyd/blob/master/whydJS/app/templates/feed.js) (which indentation is completely broken, for some reason => needs fixing), based on the value of the `format` parameter of any track list endpoint.

Suggestion: create files feedEmbedV3.html and feedEmbedV3.css, and add them to feed.js, in a way to not break existing embeds (they should still be able to use V1 or V2).

**Comment by adrienjoly** [comment]
Nobody asked for this in a long time.
