### ISSUE TITLE
DEV: Create a (docker) container to simplify local execution of openwhyd

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#56]
Objective: simplify execution of openwhyd's app and database servers, on any host, while avoiding conflicts and version mismatchs

=> instead of asking volunteers/contributors to install all the dependencies, enable them to make it run on their machine by typing just one command.

Anybody had experience with setting up a docker container properly for a nodejs + mongodb app?

**Comment by adrienjoly** [comment]
work in progress, by @nicolasleger: https://github.com/openwhyd/openwhyd/pull/57

**Comment by adrienjoly** [comment]
Congrats, @nicolasleger for your awesome pull request! It works like a charm!

I still have a few questions for Docker noobs like myself:

- [ ] how to run `npm test` in the docker container?
- [ ] how to restart the web server in the docker container, after updating its source code locally?

**Comment by nicolasleger** [comment]
- `docker-compose exec web npm test` but might be proper to create either a separate `Dockerfile` or a dedicated `test` service in `docker-compose.yml`
- `docker-compose restart web` or automatically with `nodemon` or equivalent

**Comment by adrienjoly** [comment]
awesome, thank you for your replies, nicolas!
