### ISSUE TITLE
DEV : Start up blocks without error when connecting to MongoDB version >3.2.7

### ISSUE THREAD

**Issue by nicolasleger** [openwhyd/openwhyd#58]
Triggered via `npm run run` the line `mongodb.MongoClient.connect(url, options, function(err, db){` does not call the callback function.

Failing tested latest node and MongoDB versions `v3.2.11` / `v3.4.6` and `mongodb@1.4.40` for module. Also tried with the `?w=1` parameter https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html.

Might come from the npm `mongodb` module (or dependencies) or MongoDB version, or node ?

```
├─┬ mongodb@1.4.40
│ ├─┬ bson@0.2.22
│ │ └── nan@1.8.4
```

See comments of https://github.com/openwhyd/openwhyd/pull/57#issuecomment-314760467

**Comment by adrienjoly** [comment]
Thanks for having taken the time to write this detailed issue, Nicolas! 👌

**Comment by adrienjoly** [comment]
I'm going to upgrade Mongodb driver to version 2, on production, to see if it works as expected. (see https://github.com/openwhyd/openwhyd/pull/54)

My plan is to implement a fix for this issue directly on the version 2, instead of doing it on an old version. Makes sense?

**Comment by adrienjoly** [comment]
Closed in favor to #236.
