### ISSUE TITLE
Safety: find and prevent errors from production logs

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#90]
EDITED ON 26/10/2017:

> What I have in mind is a tool that would look for lines containing error or warning (by doing something similar to a tail -f mylog.out | grep error), group these lines by type of error (or warning), then send a summary every week (e.g. by email).
> 
> We don't need a fancy dashboard, just a tool that would be able to do this grouping from our log files and send us a summary.

**Comment by znk** [comment]
Is it an issue? Prod logs are great to help technical community feedback.

Before addressing this issue, there would be a need of modern build pipeline of scripts, it will help to whether silent errors or based on environment. For now, it seems to me that static files are served directly ( `whydJS/public/js` folder)

So far, I saw logs from:
- [Google Analytics](https://github.com/openwhyd/openwhyd/blob/d5935d7f1001e682174fdcba6b79cbda23e97ecc/whydJS/public/js/whydtr.js#L54)
- [jQueryMigrate, this one needs only `jQuery.migrateMute = true`](https://github.com/openwhyd/openwhyd/blob/ce1cb979bb2396b94016bda3fb3388fd20f9e402/whydJS/public/js/jquery-migrate-1.2.1.js#L17) 
- WhydPlayer, who depends from your Playem

**Comment by adrienjoly** [comment]
I was thinking of server logs, actually.

Today, they are stored in log files on the production server, and there is no way to monitor to alert developers in case of critical errors.

Do you have any service to recommend for that?
 (Something that we could use for free, as an open source project)

**Comment by josselinchevalay** [comment]
hi, 

in the first step maybe you can use that : https://mmonit.com/monit/. if you need more feature you can see  that  : 

- https://logz.io/learn/complete-guide-elk-stack/ (replace logstash by filebeat is more efficient).
- https://github.com/stefanprodan/dockprom (it's cool you can simply integrated that a alert in slack). 
- https://www.influxdata.com/time-series-platform/ (just see that but i'm not tested). 
- https://www.datadoghq.com/ (SAAS solution). 

Regards

**Comment by adrienjoly** [comment]
> You can also use Monit to monitor files, directories and filesystems on localhost. Monit can monitor these items for changes, such as timestamps changes, checksum changes or size changes. This is also useful for security reasons - you can monitor the md5 or sha1 checksum of files that should not change and get an alert or perform an action if they should change.

Interesting, indeed, @josselinchevalay!

Is this the right tool to aggregate warning and error messages by type, so that we can focus on the most important issues to solve first?

What I have in mind is a tool that would look for lines containing `error` or `warning` (by doing something similar to a `tail -f mylog.out | grep error`), group these lines by type of `error` (or `warning`), then send a summary every week (e.g. by email).

We don't need a fancy dashboard, just a tool that would be able to do this grouping from our log files and send us a summary.

**Comment by josselinchevalay** [comment]
hi @adrienjoly 

for example if you choose ELK stack your logstash instance can get all logs on elasticsearch after with kibana you can create a dashboard for exemple all logs where ERROR appear or other detail. 

With my second propal you have the same system and you can add a bot to follow a metric and when this metric is to upper you can send a slack message. 

So ype it's possible to "grep all Error message". 

Regards

**Comment by adrienjoly** [comment]
Both solutions sound awesome, @josselinchevalay!

Would you like to help by setting one up?

**Comment by josselinchevalay** [comment]
maybe yes i can help you tu setting the first or the second propal.

**Comment by adrienjoly** [comment]
Awesome, thanks for your offer!

What's the one that would require the fewer manipulation of our machine?

**Comment by josselinchevalay** [comment]
Two propals can run on docker so i think limit human action on your production environement.
We can test locally.  After test  you can push that into production and run docker-compose command.

**Comment by adrienjoly** [comment]
Never tried to run any docker container on our DigitalOcean instance, but I guess it must be simple enough, and the process that you propose seems very reasonable!

I'd be happy to help testing and deploying a solution like this!

**Comment by josselinchevalay** [comment]
i think we can create a new repositories under openwhyd for that. For the test we need just a log file to test filebeat (you can anonimyse that with false ip domain name etc) we need to analyze a bit log structure.

**Comment by adrienjoly** [comment]
Don't you want to host the repo on your own github account? If you really want to have it here, we could still fork it into this org afterwards, no?

I have to admit that I had forgotten about anonymization... Would you be ok to generate some log data by running Openwhyd locally, and then I'd test your container on actual production data?

**Comment by josselinchevalay** [comment]
totally reason i will see that thx.

**Comment by adrienjoly** [comment]
Server-side errors can now be tracked from Rollbar dashboard: https://rollbar.com/adrienjoly/openwhyd/?environment=production (alternative to Sentry)
